# ************* PostgreSQL Secrets *************
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: innowise
type: Opaque
stringData:
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
---
# ************* PostgreSQL Shared DB Secrets *************
apiVersion: v1
kind: Secret
metadata:
  name: shared-db-secrets
  namespace: innowise
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "postgres"
---
# ************* LocalStack Secrets *************
apiVersion: v1
kind: Secret
metadata:
  name: localstack-secrets
  namespace: innowise
type: Opaque
stringData:
  AWS_S3_ENDPOINT_URL: "http://localstack:4566"
  AWS_S3_PUBLIC_URL: "http://localstack.local"
  AWS_S3_REGION: "us-east-1"
  AWS_S3_BUCKET_NAME: "images"
  AWS_S3_ACCESS_KEY: "test"
  AWS_S3_SECRET_KEY: "test"
---
# ************* Kafka Secrets *************
apiVersion: v1
kind: Secret
metadata:
  name: kafka-secrets
  namespace: innowise
type: Opaque
stringData:
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
---
# ************* Mongo Express Secrets *************
apiVersion: v1
kind: Secret
metadata:
  name: mongo-express-secrets
  namespace: innowise
type: Opaque
stringData:
  ME_CONFIG_MONGODB_URL: "mongodb://mongo:27017/activitydb"
  ME_ADMIN_USER: "admin"
  ME_ADMIN_PASSWORD: "admin"
  ME_BASIC_AUTH_HEADER: "Basic YWRtaW46YWRtaW4="
---
# ************* Authentication Service Secrets *************
apiVersion: v1
kind: Secret
metadata:
  name: authentication-service-secrets
  namespace: innowise
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/user_db"
  AUTH_SERVICE_SECRET: "my-super-secret"
---
# ************* Activity Service Secrets *************
apiVersion: v1
kind: Secret
metadata:
  name: activity-service-secrets
  namespace: innowise
type: Opaque
stringData:
  SPRING_DATA_MONGODB_URI: "mongodb://mongo:27017/activitydb"
---
# ************* Image Service Secrets *************
apiVersion: v1
kind: Secret
metadata:
  name: image-service-secrets
  namespace: innowise
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/image_db"
  AUTH_SERVICE_SECRET: "my-super-secret"

