spring:
  application:
    name: image-service
  datasource:
    url: jdbc:postgresql://localhost:5432/image_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka:
  topics:
    partitions: 1
    replication-factor: 1

aws:
  s3:
    endpoint-url: http://localhost:4566
    public-url: http://localhost:4566
    region: us-east-1
    bucket-name: images
    access-key: test
    secret-key: test

images:
  min-bytes: 102400 # 100 KB
  max-bytes: 10485760 # 10 MB

auth:
  service:
    url: http://authentication-service:8080/api/auth/names
    secret: my-super-secret
